/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.cache.Cache
 *  com.google.common.cache.CacheBuilder
 *  com.google.common.collect.ImmutableMap$Builder
 *  javax.inject.Inject
 *  net.runelite.api.widgets.WidgetItem
 */
package net.runelite.client.plugins.ferox;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.google.common.collect.ImmutableMap;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Map;
import java.util.Objects;
import javax.inject.Inject;
import net.runelite.api.widgets.WidgetItem;
import net.runelite.client.game.ItemManager;
import net.runelite.client.plugins.ferox.FeroxConfig;
import net.runelite.client.plugins.ferox.ItemUpgradeTier;
import net.runelite.client.plugins.ferox.MathUtil;
import net.runelite.client.ui.FontManager;
import net.runelite.client.ui.overlay.WidgetItemOverlay;
import net.runelite.client.util.AsyncBufferedImage;
import net.runelite.client.util.ColorUtil;

class WeaponUpgradeOverlay
extends WidgetItemOverlay {
    private final FeroxConfig config;
    private final ItemManager itemManager;
    private static final Map<Integer, ItemUpgradeTier> ITEM_TIERS;
    private final Cache<Integer, BufferedImage> cache;

    @Inject
    WeaponUpgradeOverlay(ItemManager itemManager, FeroxConfig config) {
        this.config = config;
        this.itemManager = itemManager;
        this.showOnInventory();
        this.showOnEquipment();
        this.showOnBank();
        this.showOnInterfaces(4, 81, 1095);
        this.cache = CacheBuilder.newBuilder().concurrencyLevel(1).maximumSize(32L).build();
    }

    @Override
    public void renderItemOverlay(Graphics2D graphics, int itemId, WidgetItem widgetItem) {
        ItemUpgradeTier tier = ITEM_TIERS.getOrDefault(itemId, null);
        if (tier == null) {
            return;
        }
        if (this.config.displayTierColors()) {
            this.renderColorUnderlay(graphics, widgetItem, tier);
        }
        if (this.config.displayTierText() && widgetItem.getQuantity() <= 1) {
            this.renderTextOverlay(graphics, widgetItem, tier);
        }
    }

    private void renderColorUnderlay(Graphics2D graphics, WidgetItem widgetItem, ItemUpgradeTier tier) {
        int x = widgetItem.getCanvasLocation().getX();
        int y = widgetItem.getCanvasLocation().getY();
        int r = 32;
        int startX = (x += r / 2) - r;
        int endX = x + r;
        int startY = (y += r / 2) - r;
        int endY = y + r;
        BufferedImage cachedUnderlay = (BufferedImage)this.cache.getIfPresent((Object)widgetItem.getId());
        if (cachedUnderlay != null) {
            graphics.drawImage((Image)cachedUnderlay, startX, startY, null);
            return;
        }
        BufferedImage underlay = new BufferedImage(endX - startX, endY - startY, 2);
        Color tierColor = Objects.requireNonNull(ColorUtil.fromHex(tier.getHexColor()));
        AsyncBufferedImage image = this.itemManager.getImage(widgetItem.getId());
        float edge0 = -((float)r / 2.0f);
        for (int pX = startX; pX < endX; ++pX) {
            for (int pY = startY; pY < endY; ++pY) {
                float d = MathUtil.dist(pX, pY, x, y);
                float dist = MathUtil.smoothstep(edge0, r, d);
                float ratio = 1.0f - dist;
                int f2 = (int)(256.0f * ratio);
                int f1 = 256 - f2;
                Color color = ColorUtil.colorWithAlpha(tierColor, f2);
                graphics.setColor(color);
                if (widgetItem.getCanvasBounds().contains(pX, pY)) {
                    int localX = pX - startX - 16;
                    int localY = pY - startY - 16;
                    int rgb = image.getRGB(localX, localY);
                    int alpha = rgb >> 24 & 0xFF;
                    if (alpha != 0) continue;
                    underlay.setRGB(pX - startX, pY - startY, color.getRGB());
                    continue;
                }
                underlay.setRGB(pX - startX, pY - startY, color.getRGB());
            }
        }
        graphics.drawImage((Image)underlay, startX, startY, null);
        this.cache.put((Object)widgetItem.getId(), (Object)underlay);
    }

    private void renderTextOverlay(Graphics2D graphics, WidgetItem widgetItem, ItemUpgradeTier tier) {
        int x = widgetItem.getCanvasLocation().getX() + 2;
        int y = widgetItem.getCanvasLocation().getY() + 10;
        Color tierColor = Objects.requireNonNull(ColorUtil.fromHex(tier.getHexColor()));
        graphics.setColor(tierColor);
        graphics.setFont(FontManager.getRunescapeFont());
        graphics.drawString(tier.name(), x, y);
    }

    static {
        ImmutableMap.Builder builder = new ImmutableMap.Builder();
        builder.put((Object)59390, (Object)ItemUpgradeTier.I);
        builder.put((Object)59392, (Object)ItemUpgradeTier.II);
        builder.put((Object)59394, (Object)ItemUpgradeTier.III);
        builder.put((Object)59396, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59398, (Object)ItemUpgradeTier.V);
        builder.put((Object)59400, (Object)ItemUpgradeTier.I);
        builder.put((Object)59402, (Object)ItemUpgradeTier.II);
        builder.put((Object)59404, (Object)ItemUpgradeTier.III);
        builder.put((Object)59406, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59408, (Object)ItemUpgradeTier.V);
        builder.put((Object)59730, (Object)ItemUpgradeTier.I);
        builder.put((Object)59732, (Object)ItemUpgradeTier.II);
        builder.put((Object)59734, (Object)ItemUpgradeTier.III);
        builder.put((Object)59736, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59738, (Object)ItemUpgradeTier.V);
        builder.put((Object)58920, (Object)ItemUpgradeTier.I);
        builder.put((Object)58922, (Object)ItemUpgradeTier.II);
        builder.put((Object)58924, (Object)ItemUpgradeTier.III);
        builder.put((Object)58926, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58928, (Object)ItemUpgradeTier.V);
        builder.put((Object)59740, (Object)ItemUpgradeTier.I);
        builder.put((Object)59742, (Object)ItemUpgradeTier.II);
        builder.put((Object)59744, (Object)ItemUpgradeTier.III);
        builder.put((Object)59746, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59748, (Object)ItemUpgradeTier.V);
        builder.put((Object)59750, (Object)ItemUpgradeTier.I);
        builder.put((Object)59752, (Object)ItemUpgradeTier.II);
        builder.put((Object)59754, (Object)ItemUpgradeTier.III);
        builder.put((Object)59756, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59758, (Object)ItemUpgradeTier.V);
        builder.put((Object)58930, (Object)ItemUpgradeTier.I);
        builder.put((Object)58932, (Object)ItemUpgradeTier.II);
        builder.put((Object)58934, (Object)ItemUpgradeTier.III);
        builder.put((Object)58936, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58938, (Object)ItemUpgradeTier.V);
        builder.put((Object)59410, (Object)ItemUpgradeTier.I);
        builder.put((Object)59412, (Object)ItemUpgradeTier.II);
        builder.put((Object)59414, (Object)ItemUpgradeTier.III);
        builder.put((Object)59416, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59418, (Object)ItemUpgradeTier.V);
        builder.put((Object)58940, (Object)ItemUpgradeTier.I);
        builder.put((Object)58942, (Object)ItemUpgradeTier.II);
        builder.put((Object)58944, (Object)ItemUpgradeTier.III);
        builder.put((Object)58946, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58948, (Object)ItemUpgradeTier.V);
        builder.put((Object)58950, (Object)ItemUpgradeTier.I);
        builder.put((Object)58952, (Object)ItemUpgradeTier.II);
        builder.put((Object)58954, (Object)ItemUpgradeTier.III);
        builder.put((Object)58956, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58958, (Object)ItemUpgradeTier.V);
        builder.put((Object)58960, (Object)ItemUpgradeTier.I);
        builder.put((Object)58962, (Object)ItemUpgradeTier.II);
        builder.put((Object)58964, (Object)ItemUpgradeTier.III);
        builder.put((Object)58966, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58968, (Object)ItemUpgradeTier.V);
        builder.put((Object)58970, (Object)ItemUpgradeTier.I);
        builder.put((Object)58972, (Object)ItemUpgradeTier.II);
        builder.put((Object)58974, (Object)ItemUpgradeTier.III);
        builder.put((Object)58976, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58978, (Object)ItemUpgradeTier.V);
        builder.put((Object)59420, (Object)ItemUpgradeTier.I);
        builder.put((Object)59422, (Object)ItemUpgradeTier.II);
        builder.put((Object)59424, (Object)ItemUpgradeTier.III);
        builder.put((Object)59426, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59428, (Object)ItemUpgradeTier.V);
        builder.put((Object)59430, (Object)ItemUpgradeTier.I);
        builder.put((Object)59432, (Object)ItemUpgradeTier.II);
        builder.put((Object)59434, (Object)ItemUpgradeTier.III);
        builder.put((Object)59436, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59438, (Object)ItemUpgradeTier.V);
        builder.put((Object)59440, (Object)ItemUpgradeTier.I);
        builder.put((Object)59442, (Object)ItemUpgradeTier.II);
        builder.put((Object)59444, (Object)ItemUpgradeTier.III);
        builder.put((Object)59446, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59448, (Object)ItemUpgradeTier.V);
        builder.put((Object)59450, (Object)ItemUpgradeTier.I);
        builder.put((Object)59452, (Object)ItemUpgradeTier.II);
        builder.put((Object)59454, (Object)ItemUpgradeTier.III);
        builder.put((Object)59456, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59458, (Object)ItemUpgradeTier.V);
        builder.put((Object)59460, (Object)ItemUpgradeTier.I);
        builder.put((Object)59462, (Object)ItemUpgradeTier.II);
        builder.put((Object)59464, (Object)ItemUpgradeTier.III);
        builder.put((Object)59466, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59468, (Object)ItemUpgradeTier.V);
        builder.put((Object)59470, (Object)ItemUpgradeTier.I);
        builder.put((Object)59472, (Object)ItemUpgradeTier.II);
        builder.put((Object)59474, (Object)ItemUpgradeTier.III);
        builder.put((Object)59476, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59478, (Object)ItemUpgradeTier.V);
        builder.put((Object)59340, (Object)ItemUpgradeTier.I);
        builder.put((Object)59342, (Object)ItemUpgradeTier.II);
        builder.put((Object)59344, (Object)ItemUpgradeTier.III);
        builder.put((Object)59346, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59348, (Object)ItemUpgradeTier.V);
        builder.put((Object)59480, (Object)ItemUpgradeTier.I);
        builder.put((Object)59482, (Object)ItemUpgradeTier.II);
        builder.put((Object)59484, (Object)ItemUpgradeTier.III);
        builder.put((Object)59486, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59488, (Object)ItemUpgradeTier.V);
        builder.put((Object)59490, (Object)ItemUpgradeTier.I);
        builder.put((Object)59492, (Object)ItemUpgradeTier.II);
        builder.put((Object)59494, (Object)ItemUpgradeTier.III);
        builder.put((Object)59496, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59498, (Object)ItemUpgradeTier.V);
        builder.put((Object)59500, (Object)ItemUpgradeTier.I);
        builder.put((Object)59502, (Object)ItemUpgradeTier.II);
        builder.put((Object)59504, (Object)ItemUpgradeTier.III);
        builder.put((Object)59506, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59508, (Object)ItemUpgradeTier.V);
        builder.put((Object)59510, (Object)ItemUpgradeTier.I);
        builder.put((Object)59512, (Object)ItemUpgradeTier.II);
        builder.put((Object)59514, (Object)ItemUpgradeTier.III);
        builder.put((Object)59516, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59518, (Object)ItemUpgradeTier.V);
        builder.put((Object)59520, (Object)ItemUpgradeTier.I);
        builder.put((Object)59522, (Object)ItemUpgradeTier.II);
        builder.put((Object)59524, (Object)ItemUpgradeTier.III);
        builder.put((Object)59526, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59528, (Object)ItemUpgradeTier.V);
        builder.put((Object)59530, (Object)ItemUpgradeTier.I);
        builder.put((Object)59532, (Object)ItemUpgradeTier.II);
        builder.put((Object)59534, (Object)ItemUpgradeTier.III);
        builder.put((Object)59536, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59538, (Object)ItemUpgradeTier.V);
        builder.put((Object)59540, (Object)ItemUpgradeTier.I);
        builder.put((Object)59542, (Object)ItemUpgradeTier.II);
        builder.put((Object)59544, (Object)ItemUpgradeTier.III);
        builder.put((Object)59546, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59548, (Object)ItemUpgradeTier.V);
        builder.put((Object)59550, (Object)ItemUpgradeTier.I);
        builder.put((Object)59552, (Object)ItemUpgradeTier.II);
        builder.put((Object)59554, (Object)ItemUpgradeTier.III);
        builder.put((Object)59556, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59558, (Object)ItemUpgradeTier.V);
        builder.put((Object)59560, (Object)ItemUpgradeTier.I);
        builder.put((Object)59562, (Object)ItemUpgradeTier.II);
        builder.put((Object)59564, (Object)ItemUpgradeTier.III);
        builder.put((Object)59566, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59568, (Object)ItemUpgradeTier.V);
        builder.put((Object)59570, (Object)ItemUpgradeTier.I);
        builder.put((Object)59572, (Object)ItemUpgradeTier.II);
        builder.put((Object)59574, (Object)ItemUpgradeTier.III);
        builder.put((Object)59576, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59578, (Object)ItemUpgradeTier.V);
        builder.put((Object)59580, (Object)ItemUpgradeTier.I);
        builder.put((Object)59582, (Object)ItemUpgradeTier.II);
        builder.put((Object)59584, (Object)ItemUpgradeTier.III);
        builder.put((Object)59586, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59588, (Object)ItemUpgradeTier.V);
        builder.put((Object)59590, (Object)ItemUpgradeTier.I);
        builder.put((Object)59592, (Object)ItemUpgradeTier.II);
        builder.put((Object)59594, (Object)ItemUpgradeTier.III);
        builder.put((Object)59596, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59598, (Object)ItemUpgradeTier.V);
        builder.put((Object)59600, (Object)ItemUpgradeTier.I);
        builder.put((Object)59602, (Object)ItemUpgradeTier.II);
        builder.put((Object)59604, (Object)ItemUpgradeTier.III);
        builder.put((Object)59606, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59608, (Object)ItemUpgradeTier.V);
        builder.put((Object)59610, (Object)ItemUpgradeTier.I);
        builder.put((Object)59612, (Object)ItemUpgradeTier.II);
        builder.put((Object)59614, (Object)ItemUpgradeTier.III);
        builder.put((Object)59616, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59618, (Object)ItemUpgradeTier.V);
        builder.put((Object)59660, (Object)ItemUpgradeTier.I);
        builder.put((Object)59662, (Object)ItemUpgradeTier.II);
        builder.put((Object)59664, (Object)ItemUpgradeTier.III);
        builder.put((Object)59666, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59668, (Object)ItemUpgradeTier.V);
        builder.put((Object)59620, (Object)ItemUpgradeTier.I);
        builder.put((Object)59622, (Object)ItemUpgradeTier.II);
        builder.put((Object)59624, (Object)ItemUpgradeTier.III);
        builder.put((Object)59626, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59628, (Object)ItemUpgradeTier.V);
        builder.put((Object)59670, (Object)ItemUpgradeTier.I);
        builder.put((Object)59672, (Object)ItemUpgradeTier.II);
        builder.put((Object)59674, (Object)ItemUpgradeTier.III);
        builder.put((Object)59676, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59678, (Object)ItemUpgradeTier.V);
        builder.put((Object)59680, (Object)ItemUpgradeTier.I);
        builder.put((Object)59682, (Object)ItemUpgradeTier.II);
        builder.put((Object)59684, (Object)ItemUpgradeTier.III);
        builder.put((Object)59686, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59688, (Object)ItemUpgradeTier.V);
        builder.put((Object)59630, (Object)ItemUpgradeTier.I);
        builder.put((Object)59632, (Object)ItemUpgradeTier.II);
        builder.put((Object)59634, (Object)ItemUpgradeTier.III);
        builder.put((Object)59636, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59638, (Object)ItemUpgradeTier.V);
        builder.put((Object)59690, (Object)ItemUpgradeTier.I);
        builder.put((Object)59692, (Object)ItemUpgradeTier.II);
        builder.put((Object)59694, (Object)ItemUpgradeTier.III);
        builder.put((Object)59696, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59698, (Object)ItemUpgradeTier.V);
        builder.put((Object)59700, (Object)ItemUpgradeTier.I);
        builder.put((Object)59702, (Object)ItemUpgradeTier.II);
        builder.put((Object)59704, (Object)ItemUpgradeTier.III);
        builder.put((Object)59706, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59708, (Object)ItemUpgradeTier.V);
        builder.put((Object)59640, (Object)ItemUpgradeTier.I);
        builder.put((Object)59642, (Object)ItemUpgradeTier.II);
        builder.put((Object)59644, (Object)ItemUpgradeTier.III);
        builder.put((Object)59646, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59648, (Object)ItemUpgradeTier.V);
        builder.put((Object)59710, (Object)ItemUpgradeTier.I);
        builder.put((Object)59712, (Object)ItemUpgradeTier.II);
        builder.put((Object)59714, (Object)ItemUpgradeTier.III);
        builder.put((Object)59716, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59718, (Object)ItemUpgradeTier.V);
        builder.put((Object)59650, (Object)ItemUpgradeTier.I);
        builder.put((Object)59652, (Object)ItemUpgradeTier.II);
        builder.put((Object)59654, (Object)ItemUpgradeTier.III);
        builder.put((Object)59656, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59658, (Object)ItemUpgradeTier.V);
        builder.put((Object)59720, (Object)ItemUpgradeTier.I);
        builder.put((Object)59722, (Object)ItemUpgradeTier.II);
        builder.put((Object)59724, (Object)ItemUpgradeTier.III);
        builder.put((Object)59726, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59728, (Object)ItemUpgradeTier.V);
        builder.put((Object)59760, (Object)ItemUpgradeTier.I);
        builder.put((Object)59762, (Object)ItemUpgradeTier.II);
        builder.put((Object)59764, (Object)ItemUpgradeTier.III);
        builder.put((Object)59766, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59768, (Object)ItemUpgradeTier.V);
        builder.put((Object)59770, (Object)ItemUpgradeTier.I);
        builder.put((Object)59772, (Object)ItemUpgradeTier.II);
        builder.put((Object)59774, (Object)ItemUpgradeTier.III);
        builder.put((Object)59776, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59778, (Object)ItemUpgradeTier.V);
        builder.put((Object)59780, (Object)ItemUpgradeTier.I);
        builder.put((Object)59782, (Object)ItemUpgradeTier.II);
        builder.put((Object)59784, (Object)ItemUpgradeTier.III);
        builder.put((Object)59786, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59788, (Object)ItemUpgradeTier.V);
        builder.put((Object)59790, (Object)ItemUpgradeTier.I);
        builder.put((Object)59792, (Object)ItemUpgradeTier.II);
        builder.put((Object)59794, (Object)ItemUpgradeTier.III);
        builder.put((Object)59796, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59798, (Object)ItemUpgradeTier.V);
        builder.put((Object)59800, (Object)ItemUpgradeTier.I);
        builder.put((Object)59802, (Object)ItemUpgradeTier.II);
        builder.put((Object)59804, (Object)ItemUpgradeTier.III);
        builder.put((Object)59806, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59808, (Object)ItemUpgradeTier.V);
        builder.put((Object)59810, (Object)ItemUpgradeTier.I);
        builder.put((Object)59812, (Object)ItemUpgradeTier.II);
        builder.put((Object)59814, (Object)ItemUpgradeTier.III);
        builder.put((Object)59816, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59818, (Object)ItemUpgradeTier.V);
        builder.put((Object)59820, (Object)ItemUpgradeTier.I);
        builder.put((Object)59822, (Object)ItemUpgradeTier.II);
        builder.put((Object)59824, (Object)ItemUpgradeTier.III);
        builder.put((Object)59826, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59828, (Object)ItemUpgradeTier.V);
        builder.put((Object)59830, (Object)ItemUpgradeTier.I);
        builder.put((Object)59832, (Object)ItemUpgradeTier.II);
        builder.put((Object)59834, (Object)ItemUpgradeTier.III);
        builder.put((Object)59836, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59838, (Object)ItemUpgradeTier.V);
        builder.put((Object)59840, (Object)ItemUpgradeTier.I);
        builder.put((Object)59842, (Object)ItemUpgradeTier.II);
        builder.put((Object)59844, (Object)ItemUpgradeTier.III);
        builder.put((Object)59846, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59848, (Object)ItemUpgradeTier.V);
        builder.put((Object)58980, (Object)ItemUpgradeTier.I);
        builder.put((Object)58982, (Object)ItemUpgradeTier.II);
        builder.put((Object)58984, (Object)ItemUpgradeTier.III);
        builder.put((Object)58986, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58988, (Object)ItemUpgradeTier.V);
        builder.put((Object)59350, (Object)ItemUpgradeTier.I);
        builder.put((Object)59352, (Object)ItemUpgradeTier.II);
        builder.put((Object)59354, (Object)ItemUpgradeTier.III);
        builder.put((Object)59356, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59358, (Object)ItemUpgradeTier.V);
        builder.put((Object)58760, (Object)ItemUpgradeTier.I);
        builder.put((Object)58762, (Object)ItemUpgradeTier.II);
        builder.put((Object)58764, (Object)ItemUpgradeTier.III);
        builder.put((Object)58766, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58768, (Object)ItemUpgradeTier.V);
        builder.put((Object)58770, (Object)ItemUpgradeTier.I);
        builder.put((Object)58772, (Object)ItemUpgradeTier.II);
        builder.put((Object)58774, (Object)ItemUpgradeTier.III);
        builder.put((Object)58776, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58778, (Object)ItemUpgradeTier.V);
        builder.put((Object)58780, (Object)ItemUpgradeTier.I);
        builder.put((Object)58782, (Object)ItemUpgradeTier.II);
        builder.put((Object)58784, (Object)ItemUpgradeTier.III);
        builder.put((Object)58786, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58788, (Object)ItemUpgradeTier.V);
        builder.put((Object)58790, (Object)ItemUpgradeTier.I);
        builder.put((Object)58792, (Object)ItemUpgradeTier.II);
        builder.put((Object)58794, (Object)ItemUpgradeTier.III);
        builder.put((Object)58796, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58798, (Object)ItemUpgradeTier.V);
        builder.put((Object)58800, (Object)ItemUpgradeTier.I);
        builder.put((Object)58802, (Object)ItemUpgradeTier.II);
        builder.put((Object)58804, (Object)ItemUpgradeTier.III);
        builder.put((Object)58806, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58808, (Object)ItemUpgradeTier.V);
        builder.put((Object)58640, (Object)ItemUpgradeTier.I);
        builder.put((Object)58642, (Object)ItemUpgradeTier.II);
        builder.put((Object)58644, (Object)ItemUpgradeTier.III);
        builder.put((Object)58646, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58648, (Object)ItemUpgradeTier.V);
        builder.put((Object)58650, (Object)ItemUpgradeTier.I);
        builder.put((Object)58652, (Object)ItemUpgradeTier.II);
        builder.put((Object)58654, (Object)ItemUpgradeTier.III);
        builder.put((Object)58656, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58658, (Object)ItemUpgradeTier.V);
        builder.put((Object)58660, (Object)ItemUpgradeTier.I);
        builder.put((Object)58662, (Object)ItemUpgradeTier.II);
        builder.put((Object)58664, (Object)ItemUpgradeTier.III);
        builder.put((Object)58666, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58668, (Object)ItemUpgradeTier.V);
        builder.put((Object)58670, (Object)ItemUpgradeTier.I);
        builder.put((Object)58672, (Object)ItemUpgradeTier.II);
        builder.put((Object)58674, (Object)ItemUpgradeTier.III);
        builder.put((Object)58676, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58678, (Object)ItemUpgradeTier.V);
        builder.put((Object)59360, (Object)ItemUpgradeTier.I);
        builder.put((Object)59362, (Object)ItemUpgradeTier.II);
        builder.put((Object)59364, (Object)ItemUpgradeTier.III);
        builder.put((Object)59366, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59368, (Object)ItemUpgradeTier.V);
        builder.put((Object)58680, (Object)ItemUpgradeTier.I);
        builder.put((Object)58682, (Object)ItemUpgradeTier.II);
        builder.put((Object)58684, (Object)ItemUpgradeTier.III);
        builder.put((Object)58686, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58688, (Object)ItemUpgradeTier.V);
        builder.put((Object)58690, (Object)ItemUpgradeTier.I);
        builder.put((Object)58692, (Object)ItemUpgradeTier.II);
        builder.put((Object)58694, (Object)ItemUpgradeTier.III);
        builder.put((Object)58696, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58698, (Object)ItemUpgradeTier.V);
        builder.put((Object)58510, (Object)ItemUpgradeTier.I);
        builder.put((Object)58512, (Object)ItemUpgradeTier.II);
        builder.put((Object)58514, (Object)ItemUpgradeTier.III);
        builder.put((Object)58516, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58518, (Object)ItemUpgradeTier.V);
        builder.put((Object)59370, (Object)ItemUpgradeTier.I);
        builder.put((Object)59372, (Object)ItemUpgradeTier.II);
        builder.put((Object)59374, (Object)ItemUpgradeTier.III);
        builder.put((Object)59376, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59378, (Object)ItemUpgradeTier.V);
        builder.put((Object)59380, (Object)ItemUpgradeTier.I);
        builder.put((Object)59382, (Object)ItemUpgradeTier.II);
        builder.put((Object)59384, (Object)ItemUpgradeTier.III);
        builder.put((Object)59386, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59388, (Object)ItemUpgradeTier.V);
        builder.put((Object)58500, (Object)ItemUpgradeTier.I);
        builder.put((Object)58502, (Object)ItemUpgradeTier.II);
        builder.put((Object)58504, (Object)ItemUpgradeTier.III);
        builder.put((Object)58506, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58508, (Object)ItemUpgradeTier.V);
        builder.put((Object)58700, (Object)ItemUpgradeTier.I);
        builder.put((Object)58702, (Object)ItemUpgradeTier.II);
        builder.put((Object)58704, (Object)ItemUpgradeTier.III);
        builder.put((Object)58706, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58708, (Object)ItemUpgradeTier.V);
        builder.put((Object)58710, (Object)ItemUpgradeTier.I);
        builder.put((Object)58712, (Object)ItemUpgradeTier.II);
        builder.put((Object)58714, (Object)ItemUpgradeTier.III);
        builder.put((Object)58716, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58718, (Object)ItemUpgradeTier.V);
        builder.put((Object)58990, (Object)ItemUpgradeTier.I);
        builder.put((Object)58992, (Object)ItemUpgradeTier.II);
        builder.put((Object)58994, (Object)ItemUpgradeTier.III);
        builder.put((Object)58996, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58998, (Object)ItemUpgradeTier.V);
        builder.put((Object)58740, (Object)ItemUpgradeTier.I);
        builder.put((Object)58742, (Object)ItemUpgradeTier.II);
        builder.put((Object)58744, (Object)ItemUpgradeTier.III);
        builder.put((Object)58746, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58748, (Object)ItemUpgradeTier.V);
        builder.put((Object)58750, (Object)ItemUpgradeTier.I);
        builder.put((Object)58752, (Object)ItemUpgradeTier.II);
        builder.put((Object)58754, (Object)ItemUpgradeTier.III);
        builder.put((Object)58756, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58758, (Object)ItemUpgradeTier.V);
        builder.put((Object)59070, (Object)ItemUpgradeTier.I);
        builder.put((Object)59072, (Object)ItemUpgradeTier.II);
        builder.put((Object)59074, (Object)ItemUpgradeTier.III);
        builder.put((Object)59076, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59078, (Object)ItemUpgradeTier.V);
        builder.put((Object)59080, (Object)ItemUpgradeTier.I);
        builder.put((Object)59082, (Object)ItemUpgradeTier.II);
        builder.put((Object)59084, (Object)ItemUpgradeTier.III);
        builder.put((Object)59086, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59088, (Object)ItemUpgradeTier.V);
        builder.put((Object)59090, (Object)ItemUpgradeTier.I);
        builder.put((Object)59092, (Object)ItemUpgradeTier.II);
        builder.put((Object)59094, (Object)ItemUpgradeTier.III);
        builder.put((Object)59096, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59098, (Object)ItemUpgradeTier.V);
        builder.put((Object)59100, (Object)ItemUpgradeTier.I);
        builder.put((Object)59102, (Object)ItemUpgradeTier.II);
        builder.put((Object)59104, (Object)ItemUpgradeTier.III);
        builder.put((Object)59106, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59108, (Object)ItemUpgradeTier.V);
        builder.put((Object)59110, (Object)ItemUpgradeTier.I);
        builder.put((Object)59112, (Object)ItemUpgradeTier.II);
        builder.put((Object)59114, (Object)ItemUpgradeTier.III);
        builder.put((Object)59116, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59118, (Object)ItemUpgradeTier.V);
        builder.put((Object)59120, (Object)ItemUpgradeTier.I);
        builder.put((Object)59122, (Object)ItemUpgradeTier.II);
        builder.put((Object)59124, (Object)ItemUpgradeTier.III);
        builder.put((Object)59126, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59128, (Object)ItemUpgradeTier.V);
        builder.put((Object)59130, (Object)ItemUpgradeTier.I);
        builder.put((Object)59132, (Object)ItemUpgradeTier.II);
        builder.put((Object)59134, (Object)ItemUpgradeTier.III);
        builder.put((Object)59136, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59138, (Object)ItemUpgradeTier.V);
        builder.put((Object)58520, (Object)ItemUpgradeTier.I);
        builder.put((Object)58522, (Object)ItemUpgradeTier.II);
        builder.put((Object)58524, (Object)ItemUpgradeTier.III);
        builder.put((Object)58526, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58528, (Object)ItemUpgradeTier.V);
        builder.put((Object)58530, (Object)ItemUpgradeTier.I);
        builder.put((Object)58532, (Object)ItemUpgradeTier.II);
        builder.put((Object)58534, (Object)ItemUpgradeTier.III);
        builder.put((Object)58536, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58538, (Object)ItemUpgradeTier.V);
        builder.put((Object)58540, (Object)ItemUpgradeTier.I);
        builder.put((Object)58542, (Object)ItemUpgradeTier.II);
        builder.put((Object)58544, (Object)ItemUpgradeTier.III);
        builder.put((Object)58546, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58548, (Object)ItemUpgradeTier.V);
        builder.put((Object)58550, (Object)ItemUpgradeTier.I);
        builder.put((Object)58552, (Object)ItemUpgradeTier.II);
        builder.put((Object)58554, (Object)ItemUpgradeTier.III);
        builder.put((Object)58556, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58558, (Object)ItemUpgradeTier.V);
        builder.put((Object)58560, (Object)ItemUpgradeTier.I);
        builder.put((Object)58562, (Object)ItemUpgradeTier.II);
        builder.put((Object)58564, (Object)ItemUpgradeTier.III);
        builder.put((Object)58566, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58568, (Object)ItemUpgradeTier.V);
        builder.put((Object)58570, (Object)ItemUpgradeTier.I);
        builder.put((Object)58572, (Object)ItemUpgradeTier.II);
        builder.put((Object)58574, (Object)ItemUpgradeTier.III);
        builder.put((Object)58576, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58578, (Object)ItemUpgradeTier.V);
        builder.put((Object)58580, (Object)ItemUpgradeTier.I);
        builder.put((Object)58582, (Object)ItemUpgradeTier.II);
        builder.put((Object)58584, (Object)ItemUpgradeTier.III);
        builder.put((Object)58586, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58588, (Object)ItemUpgradeTier.V);
        builder.put((Object)58590, (Object)ItemUpgradeTier.I);
        builder.put((Object)58592, (Object)ItemUpgradeTier.II);
        builder.put((Object)58594, (Object)ItemUpgradeTier.III);
        builder.put((Object)58596, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58598, (Object)ItemUpgradeTier.V);
        builder.put((Object)58600, (Object)ItemUpgradeTier.I);
        builder.put((Object)58602, (Object)ItemUpgradeTier.II);
        builder.put((Object)58604, (Object)ItemUpgradeTier.III);
        builder.put((Object)58606, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58608, (Object)ItemUpgradeTier.V);
        builder.put((Object)58610, (Object)ItemUpgradeTier.I);
        builder.put((Object)58612, (Object)ItemUpgradeTier.II);
        builder.put((Object)58614, (Object)ItemUpgradeTier.III);
        builder.put((Object)58616, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58618, (Object)ItemUpgradeTier.V);
        builder.put((Object)58620, (Object)ItemUpgradeTier.I);
        builder.put((Object)58622, (Object)ItemUpgradeTier.II);
        builder.put((Object)58624, (Object)ItemUpgradeTier.III);
        builder.put((Object)58626, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58628, (Object)ItemUpgradeTier.V);
        builder.put((Object)58630, (Object)ItemUpgradeTier.I);
        builder.put((Object)58632, (Object)ItemUpgradeTier.II);
        builder.put((Object)58634, (Object)ItemUpgradeTier.III);
        builder.put((Object)58636, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58638, (Object)ItemUpgradeTier.V);
        builder.put((Object)58720, (Object)ItemUpgradeTier.I);
        builder.put((Object)58722, (Object)ItemUpgradeTier.II);
        builder.put((Object)58724, (Object)ItemUpgradeTier.III);
        builder.put((Object)58726, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58728, (Object)ItemUpgradeTier.V);
        builder.put((Object)59140, (Object)ItemUpgradeTier.I);
        builder.put((Object)59142, (Object)ItemUpgradeTier.II);
        builder.put((Object)59144, (Object)ItemUpgradeTier.III);
        builder.put((Object)59146, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59148, (Object)ItemUpgradeTier.V);
        builder.put((Object)59150, (Object)ItemUpgradeTier.I);
        builder.put((Object)59152, (Object)ItemUpgradeTier.II);
        builder.put((Object)59154, (Object)ItemUpgradeTier.III);
        builder.put((Object)59156, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59158, (Object)ItemUpgradeTier.V);
        builder.put((Object)59160, (Object)ItemUpgradeTier.I);
        builder.put((Object)59162, (Object)ItemUpgradeTier.II);
        builder.put((Object)59164, (Object)ItemUpgradeTier.III);
        builder.put((Object)59166, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59168, (Object)ItemUpgradeTier.V);
        builder.put((Object)59170, (Object)ItemUpgradeTier.I);
        builder.put((Object)59172, (Object)ItemUpgradeTier.II);
        builder.put((Object)59174, (Object)ItemUpgradeTier.III);
        builder.put((Object)59176, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59178, (Object)ItemUpgradeTier.V);
        builder.put((Object)59180, (Object)ItemUpgradeTier.I);
        builder.put((Object)59182, (Object)ItemUpgradeTier.II);
        builder.put((Object)59184, (Object)ItemUpgradeTier.III);
        builder.put((Object)59186, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59188, (Object)ItemUpgradeTier.V);
        builder.put((Object)59190, (Object)ItemUpgradeTier.I);
        builder.put((Object)59192, (Object)ItemUpgradeTier.II);
        builder.put((Object)59194, (Object)ItemUpgradeTier.III);
        builder.put((Object)59196, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59198, (Object)ItemUpgradeTier.V);
        builder.put((Object)59200, (Object)ItemUpgradeTier.I);
        builder.put((Object)59202, (Object)ItemUpgradeTier.II);
        builder.put((Object)59204, (Object)ItemUpgradeTier.III);
        builder.put((Object)59206, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59208, (Object)ItemUpgradeTier.V);
        builder.put((Object)59210, (Object)ItemUpgradeTier.I);
        builder.put((Object)59212, (Object)ItemUpgradeTier.II);
        builder.put((Object)59214, (Object)ItemUpgradeTier.III);
        builder.put((Object)59216, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59218, (Object)ItemUpgradeTier.V);
        builder.put((Object)59220, (Object)ItemUpgradeTier.I);
        builder.put((Object)59222, (Object)ItemUpgradeTier.II);
        builder.put((Object)59224, (Object)ItemUpgradeTier.III);
        builder.put((Object)59226, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59228, (Object)ItemUpgradeTier.V);
        builder.put((Object)59230, (Object)ItemUpgradeTier.I);
        builder.put((Object)59232, (Object)ItemUpgradeTier.II);
        builder.put((Object)59234, (Object)ItemUpgradeTier.III);
        builder.put((Object)59236, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59238, (Object)ItemUpgradeTier.V);
        builder.put((Object)59240, (Object)ItemUpgradeTier.I);
        builder.put((Object)59242, (Object)ItemUpgradeTier.II);
        builder.put((Object)59244, (Object)ItemUpgradeTier.III);
        builder.put((Object)59246, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59248, (Object)ItemUpgradeTier.V);
        builder.put((Object)59250, (Object)ItemUpgradeTier.I);
        builder.put((Object)59252, (Object)ItemUpgradeTier.II);
        builder.put((Object)59254, (Object)ItemUpgradeTier.III);
        builder.put((Object)59256, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59258, (Object)ItemUpgradeTier.V);
        builder.put((Object)59260, (Object)ItemUpgradeTier.I);
        builder.put((Object)59262, (Object)ItemUpgradeTier.II);
        builder.put((Object)59264, (Object)ItemUpgradeTier.III);
        builder.put((Object)59266, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59268, (Object)ItemUpgradeTier.V);
        builder.put((Object)59270, (Object)ItemUpgradeTier.I);
        builder.put((Object)59272, (Object)ItemUpgradeTier.II);
        builder.put((Object)59274, (Object)ItemUpgradeTier.III);
        builder.put((Object)59276, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59278, (Object)ItemUpgradeTier.V);
        builder.put((Object)59280, (Object)ItemUpgradeTier.I);
        builder.put((Object)59282, (Object)ItemUpgradeTier.II);
        builder.put((Object)59284, (Object)ItemUpgradeTier.III);
        builder.put((Object)59286, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59288, (Object)ItemUpgradeTier.V);
        builder.put((Object)59290, (Object)ItemUpgradeTier.I);
        builder.put((Object)59292, (Object)ItemUpgradeTier.II);
        builder.put((Object)59294, (Object)ItemUpgradeTier.III);
        builder.put((Object)59296, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59298, (Object)ItemUpgradeTier.V);
        builder.put((Object)59300, (Object)ItemUpgradeTier.I);
        builder.put((Object)59302, (Object)ItemUpgradeTier.II);
        builder.put((Object)59304, (Object)ItemUpgradeTier.III);
        builder.put((Object)59306, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59308, (Object)ItemUpgradeTier.V);
        builder.put((Object)58730, (Object)ItemUpgradeTier.I);
        builder.put((Object)58732, (Object)ItemUpgradeTier.II);
        builder.put((Object)58734, (Object)ItemUpgradeTier.III);
        builder.put((Object)58736, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58738, (Object)ItemUpgradeTier.V);
        builder.put((Object)58810, (Object)ItemUpgradeTier.I);
        builder.put((Object)58812, (Object)ItemUpgradeTier.II);
        builder.put((Object)58814, (Object)ItemUpgradeTier.III);
        builder.put((Object)58816, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58818, (Object)ItemUpgradeTier.V);
        builder.put((Object)58820, (Object)ItemUpgradeTier.I);
        builder.put((Object)58822, (Object)ItemUpgradeTier.II);
        builder.put((Object)58824, (Object)ItemUpgradeTier.III);
        builder.put((Object)58826, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58828, (Object)ItemUpgradeTier.V);
        builder.put((Object)58830, (Object)ItemUpgradeTier.I);
        builder.put((Object)58832, (Object)ItemUpgradeTier.II);
        builder.put((Object)58834, (Object)ItemUpgradeTier.III);
        builder.put((Object)58836, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58838, (Object)ItemUpgradeTier.V);
        builder.put((Object)58840, (Object)ItemUpgradeTier.I);
        builder.put((Object)58842, (Object)ItemUpgradeTier.II);
        builder.put((Object)58844, (Object)ItemUpgradeTier.III);
        builder.put((Object)58846, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58848, (Object)ItemUpgradeTier.V);
        builder.put((Object)58850, (Object)ItemUpgradeTier.I);
        builder.put((Object)58852, (Object)ItemUpgradeTier.II);
        builder.put((Object)58854, (Object)ItemUpgradeTier.III);
        builder.put((Object)58856, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58858, (Object)ItemUpgradeTier.V);
        builder.put((Object)58860, (Object)ItemUpgradeTier.I);
        builder.put((Object)58862, (Object)ItemUpgradeTier.II);
        builder.put((Object)58864, (Object)ItemUpgradeTier.III);
        builder.put((Object)58866, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58868, (Object)ItemUpgradeTier.V);
        builder.put((Object)58870, (Object)ItemUpgradeTier.I);
        builder.put((Object)58872, (Object)ItemUpgradeTier.II);
        builder.put((Object)58874, (Object)ItemUpgradeTier.III);
        builder.put((Object)58876, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58878, (Object)ItemUpgradeTier.V);
        builder.put((Object)58880, (Object)ItemUpgradeTier.I);
        builder.put((Object)58882, (Object)ItemUpgradeTier.II);
        builder.put((Object)58884, (Object)ItemUpgradeTier.III);
        builder.put((Object)58886, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58888, (Object)ItemUpgradeTier.V);
        builder.put((Object)58890, (Object)ItemUpgradeTier.I);
        builder.put((Object)58892, (Object)ItemUpgradeTier.II);
        builder.put((Object)58894, (Object)ItemUpgradeTier.III);
        builder.put((Object)58896, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58898, (Object)ItemUpgradeTier.V);
        builder.put((Object)58900, (Object)ItemUpgradeTier.I);
        builder.put((Object)58902, (Object)ItemUpgradeTier.II);
        builder.put((Object)58904, (Object)ItemUpgradeTier.III);
        builder.put((Object)58906, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58908, (Object)ItemUpgradeTier.V);
        builder.put((Object)58910, (Object)ItemUpgradeTier.I);
        builder.put((Object)58912, (Object)ItemUpgradeTier.II);
        builder.put((Object)58914, (Object)ItemUpgradeTier.III);
        builder.put((Object)58916, (Object)ItemUpgradeTier.IV);
        builder.put((Object)58918, (Object)ItemUpgradeTier.V);
        builder.put((Object)59000, (Object)ItemUpgradeTier.I);
        builder.put((Object)59002, (Object)ItemUpgradeTier.II);
        builder.put((Object)59004, (Object)ItemUpgradeTier.III);
        builder.put((Object)59006, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59008, (Object)ItemUpgradeTier.V);
        builder.put((Object)59310, (Object)ItemUpgradeTier.I);
        builder.put((Object)59312, (Object)ItemUpgradeTier.II);
        builder.put((Object)59314, (Object)ItemUpgradeTier.III);
        builder.put((Object)59316, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59318, (Object)ItemUpgradeTier.V);
        builder.put((Object)59320, (Object)ItemUpgradeTier.I);
        builder.put((Object)59322, (Object)ItemUpgradeTier.II);
        builder.put((Object)59324, (Object)ItemUpgradeTier.III);
        builder.put((Object)59326, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59328, (Object)ItemUpgradeTier.V);
        builder.put((Object)59010, (Object)ItemUpgradeTier.I);
        builder.put((Object)59012, (Object)ItemUpgradeTier.II);
        builder.put((Object)59014, (Object)ItemUpgradeTier.III);
        builder.put((Object)59016, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59018, (Object)ItemUpgradeTier.V);
        builder.put((Object)59020, (Object)ItemUpgradeTier.I);
        builder.put((Object)59022, (Object)ItemUpgradeTier.II);
        builder.put((Object)59024, (Object)ItemUpgradeTier.III);
        builder.put((Object)59026, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59028, (Object)ItemUpgradeTier.V);
        builder.put((Object)59030, (Object)ItemUpgradeTier.I);
        builder.put((Object)59032, (Object)ItemUpgradeTier.II);
        builder.put((Object)59034, (Object)ItemUpgradeTier.III);
        builder.put((Object)59036, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59038, (Object)ItemUpgradeTier.V);
        builder.put((Object)59040, (Object)ItemUpgradeTier.I);
        builder.put((Object)59042, (Object)ItemUpgradeTier.II);
        builder.put((Object)59044, (Object)ItemUpgradeTier.III);
        builder.put((Object)59046, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59048, (Object)ItemUpgradeTier.V);
        builder.put((Object)59050, (Object)ItemUpgradeTier.I);
        builder.put((Object)59052, (Object)ItemUpgradeTier.II);
        builder.put((Object)59054, (Object)ItemUpgradeTier.III);
        builder.put((Object)59056, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59058, (Object)ItemUpgradeTier.V);
        builder.put((Object)59060, (Object)ItemUpgradeTier.I);
        builder.put((Object)59062, (Object)ItemUpgradeTier.II);
        builder.put((Object)59064, (Object)ItemUpgradeTier.III);
        builder.put((Object)59066, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59068, (Object)ItemUpgradeTier.V);
        builder.put((Object)59330, (Object)ItemUpgradeTier.I);
        builder.put((Object)59332, (Object)ItemUpgradeTier.II);
        builder.put((Object)59334, (Object)ItemUpgradeTier.III);
        builder.put((Object)59336, (Object)ItemUpgradeTier.IV);
        builder.put((Object)59338, (Object)ItemUpgradeTier.V);
        ITEM_TIERS = builder.build();
    }
}

